### ISSUE TITLE
Oh nãaaao, parece que uma node_modules se infiltrou no seu repositório XD

### ISSUE THREAD

**Issue by GardelJunior** [JoaoFilhoG3/livro_nodejs#1]
Provavelmente teremos que expurgá-la da existência da terra.

Que a força esteja com você jovem padawan.

**Comment by JoaoFilhoG3** [comment]
> Provavelmente teremos que expurgá-la da existência da terra.
> 
> Que a força esteja com você jovem padawan.

Obrigado mestre, distúrbio corretamente expurgado, o equilíbrio da força está novamente intacto
